apiVersion: v2
name: odrl-authorization
description: Umbrella chart to deploy FIWARE ODRL Authorization
type: application
version: 1.0.0
dependencies:
  # authorization
  - name: odrl-pap
    condition: odrl-pap.enabled
    version: 2.0.2
    repository: https://fiware.github.io/helm-charts
  - name: apisix
    condition: apisix.enabled
    version: 2.12.3
    repository: https://apache.github.io/apisix-helm-chart
