apiVersion: v1
kind: ConfigMap
metadata:
  name: opa-config
  namespace: {{ $.Release.Namespace | quote }}
  labels:
    {{- include "odrl-auth.labels" . | nindent 4 }}
data:
  opa.yaml: |-
    services:
      - name: bundle-server
        url: {{ .Values.opa.config.resourceUrl }}
    bundles:
      policies:
          service: bundle-server
          resource: policies.tar.gz
          polling:
            min_delay_seconds: {{ .Values.opa.config.policies.minDelay }}
            max_delay_seconds: {{ .Values.opa.config.policies.maxDelay }}
      methods:
          service: bundle-server
          resource: methods.tar.gz
          polling:
            min_delay_seconds: {{ .Values.opa.config.methods.minDelay }}
            max_delay_seconds: {{ .Values.opa.config.methods.maxDelay }}
      data:
          service: bundle-server
          resource: data.tar.gz
          polling:
            min_delay_seconds: {{ .Values.opa.config.data.minDelay }}
            max_delay_seconds: {{ .Values.opa.config.data.maxDelay }}
    default_decision: /policy/main/allow